### ISSUE TITLE
Issue with SPM and Bitrise

### ISSUE THREAD

**Issue by osrufung** [braze-inc/braze-ios-sdk#14]
Hi, 

That's something started to appear when we switch from the Cocoapods integration to the SPM. During the build process, only when Braze package is added in our `Package.swift` this dialog appears, blocking our current CI (Bitrise) execution. Is this something you're aware of?

<img width="997" alt="Screenshot 2022-11-08 at 11 50 02" src="https://user-images.githubusercontent.com/583458/200545593-6eafcb3c-9132-48a2-bee5-f0ca58c8e27e.png">

**Comment by lowip** [comment]
Hi @osrufung, thanks for reporting this issue.

We haven't encountered that prompt in CI so far. We are tracking it internally and will provide updates here.

Alternatively, you can reference our main repository (`https://github.com/Appboy/appboy-ios-sdk/`) in your `Package.swift`. That repository contains the exact same code, but is larger due to historical reasons.

You may also want to verify that you used the HTTPS URL for the [braze-ios-sdk](https://github.com/braze-inc/braze-ios-sdk) the repository instead of the SSH URL.
